import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>만나서 반가워요</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hello.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>저의 홈페이지에 오신걸 환영합니다!</p>
          <p>부담가지 마시고 편하게 둘러보세요!</p>
        </h1>
      </main>
      <div className={styles.main}></div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
